
[package]
name = "hello-wasm"
version = "0.1.2"
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
repository = "https://github.com/actly/hello_wasm"
authors = ["actyi <actyi@163.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
